/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemperpus;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class Jframe_dasboard extends javax.swing.JFrame {

    /**
     * Creates new form Jframe_dasboard
     */
    public Jframe_dasboard() {
        initComponents();
        dt();
        getContentPane().setBackground(Color.gray);
        scaleImage();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    DatabaseConnection.getConnection().close();
                } catch (SQLException ex) {
                    Logger.getLogger(Jframe_dasboard.class.getName()).log(Level.SEVERE, null, ex);
                }finally{
                    System.exit(0);
                }
                
                
            }
        });
    }
    public void dt(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        String dat = s.format(d);
        label_date.setText(dat);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_welcome = new javax.swing.JLabel();
        label_date = new javax.swing.JLabel();
        label_balikbuku = new javax.swing.JLabel();
        label_buku = new javax.swing.JLabel();
        label_member = new javax.swing.JLabel();
        label_pinjambuku = new javax.swing.JLabel();
        button_balikbuku = new javax.swing.JButton();
        button_buku = new javax.swing.JButton();
        button_pinjambuku = new javax.swing.JButton();
        button_member = new javax.swing.JButton();
        gambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_welcome.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        label_welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_welcome.setText("WELCOME");
        getContentPane().add(label_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 33, 326, 62));

        label_date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_date.setText("0");
        getContentPane().add(label_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, 145, -1));

        label_balikbuku.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_balikbuku.setForeground(new java.awt.Color(255, 204, 204));
        label_balikbuku.setText("Return Book");
        getContentPane().add(label_balikbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, -1, -1));

        label_buku.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_buku.setForeground(new java.awt.Color(255, 204, 204));
        label_buku.setText("Buku");
        getContentPane().add(label_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 317, -1, -1));

        label_member.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_member.setForeground(new java.awt.Color(255, 204, 204));
        label_member.setText("Member");
        getContentPane().add(label_member, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 317, -1, -1));

        label_pinjambuku.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_pinjambuku.setForeground(new java.awt.Color(255, 204, 204));
        label_pinjambuku.setText("Borrow Book");
        getContentPane().add(label_pinjambuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 540, -1, -1));

        button_balikbuku.setBackground(new java.awt.Color(255, 153, 153));
        button_balikbuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_pengembalianbuku.png"))); // NOI18N
        button_balikbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_balikbukuActionPerformed(evt);
            }
        });
        getContentPane().add(button_balikbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 361, 175, -1));

        button_buku.setBackground(new java.awt.Color(255, 153, 153));
        button_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_buku.png"))); // NOI18N
        button_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bukuActionPerformed(evt);
            }
        });
        getContentPane().add(button_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 144, 175, -1));

        button_pinjambuku.setBackground(new java.awt.Color(255, 153, 153));
        button_pinjambuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_pinjambuku.png"))); // NOI18N
        button_pinjambuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pinjambukuActionPerformed(evt);
            }
        });
        getContentPane().add(button_pinjambuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 361, 175, -1));

        button_member.setBackground(new java.awt.Color(255, 153, 153));
        button_member.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_members.png"))); // NOI18N
        button_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_memberActionPerformed(evt);
            }
        });
        getContentPane().add(button_member, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 144, 175, -1));
        getContentPane().add(gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -3, 770, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_balikbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_balikbukuActionPerformed
        Return returnFrame = new Return();
        returnFrame.setVisible(true);
    }//GEN-LAST:event_button_balikbukuActionPerformed

    private void button_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bukuActionPerformed
       ManajemenBooks bookFrame = new ManajemenBooks();
       bookFrame.setVisible(true);
    }//GEN-LAST:event_button_bukuActionPerformed

    private void button_pinjambukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pinjambukuActionPerformed
        // TODO add your handling code here:
        Pinjam pinjamFrame = new Pinjam();
        pinjamFrame.setVisible(true);
    }//GEN-LAST:event_button_pinjambukuActionPerformed

    private void button_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_memberActionPerformed
        ManajemenAnggota anggotaFrame = new ManajemenAnggota();
        anggotaFrame.setVisible(true);
    }//GEN-LAST:event_button_memberActionPerformed
public void scaleImage(){
        ImageIcon icon = new ImageIcon("background_dashboard.jpeg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(gambar.getWidth(), gambar.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        gambar.setIcon(scaledIcon);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe_dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe_dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe_dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe_dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe_dasboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_balikbuku;
    private javax.swing.JButton button_buku;
    private javax.swing.JButton button_member;
    private javax.swing.JButton button_pinjambuku;
    private javax.swing.JLabel gambar;
    private javax.swing.JLabel label_balikbuku;
    private javax.swing.JLabel label_buku;
    private javax.swing.JLabel label_date;
    private javax.swing.JLabel label_member;
    private javax.swing.JLabel label_pinjambuku;
    private javax.swing.JLabel label_welcome;
    // End of variables declaration//GEN-END:variables
}
