/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemperpus;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author user
 */
public class Jframe_dasboard extends javax.swing.JFrame {

    /**
     * Creates new form Jframe_dasboard
     */
    public Jframe_dasboard() {
        initComponents();
        dt();
        getContentPane().setBackground(Color.gray);
        
    }
    public void dt(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        String dat = s.format(d);
        label_date.setText(dat);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_welcome = new javax.swing.JLabel();
        label_date = new javax.swing.JLabel();
        label_balikbuku = new javax.swing.JLabel();
        label_buku = new javax.swing.JLabel();
        label_member = new javax.swing.JLabel();
        label_pinjambuku = new javax.swing.JLabel();
        button_balikbuku = new javax.swing.JButton();
        button_buku = new javax.swing.JButton();
        button_pinjambuku = new javax.swing.JButton();
        button_member = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_welcome.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        label_welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_welcome.setText("WELCUM");

        label_date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_date.setText("0");

        label_balikbuku.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_balikbuku.setText("Return Book");

        label_buku.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_buku.setText("Buku");

        label_member.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_member.setText("Member");

        label_pinjambuku.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_pinjambuku.setText("Borrow Book");

        button_balikbuku.setBackground(new java.awt.Color(60, 63, 65));
        button_balikbuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_pengembalianbuku.png"))); // NOI18N
        button_balikbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_balikbukuActionPerformed(evt);
            }
        });

        button_buku.setBackground(new java.awt.Color(60, 63, 65));
        button_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_buku.png"))); // NOI18N
        button_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bukuActionPerformed(evt);
            }
        });

        button_pinjambuku.setBackground(new java.awt.Color(60, 63, 65));
        button_pinjambuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_pinjambuku.png"))); // NOI18N
        button_pinjambuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pinjambukuActionPerformed(evt);
            }
        });

        button_member.setBackground(new java.awt.Color(60, 63, 65));
        button_member.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_members.png"))); // NOI18N
        button_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_memberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_date, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(label_buku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_member)
                .addGap(156, 156, 156))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(label_pinjambuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(156, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_pinjambuku, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(141, 141, 141)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_member, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(button_balikbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(label_balikbuku)
                            .addGap(16, 16, 16))))
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(label_date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(button_member))
                    .addComponent(button_buku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_buku, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_member))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_balikbuku, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_pinjambuku, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_balikbuku)
                    .addComponent(label_pinjambuku))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_balikbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_balikbukuActionPerformed
        Return returnFrame = new Return();
        returnFrame.setVisible(true);
    }//GEN-LAST:event_button_balikbukuActionPerformed

    private void button_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bukuActionPerformed
       ManajemenBuku bookFrame = new ManajemenBuku();
       bookFrame.setVisible(true);
    }//GEN-LAST:event_button_bukuActionPerformed

    private void button_pinjambukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pinjambukuActionPerformed
        // TODO add your handling code here:
        Pinjam pinjamFrame = new Pinjam();
        pinjamFrame.setVisible(true);
    }//GEN-LAST:event_button_pinjambukuActionPerformed

    private void button_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_memberActionPerformed
        // TODO add your handling code here:
        ManajemenAnggota anggotaFrame = new ManajemenAnggota();
        anggotaFrame.setVisible(true);
    }//GEN-LAST:event_button_memberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe_dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe_dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe_dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe_dasboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe_dasboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_balikbuku;
    private javax.swing.JButton button_buku;
    private javax.swing.JButton button_member;
    private javax.swing.JButton button_pinjambuku;
    private javax.swing.JLabel label_balikbuku;
    private javax.swing.JLabel label_buku;
    private javax.swing.JLabel label_date;
    private javax.swing.JLabel label_member;
    private javax.swing.JLabel label_pinjambuku;
    private javax.swing.JLabel label_welcome;
    // End of variables declaration//GEN-END:variables
}
