/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemperpus;

/**
 *
 * @author HP
 */
public class ManajemenBuku extends javax.swing.JFrame {

    /**
     * Creates new form ManajemenBuku
     */
    public ManajemenBuku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogDashboard = new javax.swing.JDialog();
        DialogBuku = new javax.swing.JDialog();
        LabelDaftarBuku = new javax.swing.JLabel();
        LabelJudulbuku = new javax.swing.JLabel();
        LabelKodebuku = new javax.swing.JLabel();
        LabelPenulisbuku = new javax.swing.JLabel();
        LabelKategoribuku = new javax.swing.JLabel();
        LabelJumlahbukutersedia = new javax.swing.JLabel();
        JawabanJudulBuku = new javax.swing.JTextField();
        JawabanKodeBuku = new javax.swing.JTextField();
        JawabanPenulisBuku = new javax.swing.JTextField();
        JawabanKategoriBuku = new javax.swing.JTextField();
        JawabanJumlahBukuTersedia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButtonTambah = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        DialogTambah = new javax.swing.JDialog();
        LabelPenambahanBuku = new javax.swing.JLabel();
        LabelJudulBuku = new javax.swing.JLabel();
        LabelKodeBuku = new javax.swing.JLabel();
        LabelPenulisBuku = new javax.swing.JLabel();
        LabelKategoriBuku = new javax.swing.JLabel();
        LabelJumlahBukuTersedia = new javax.swing.JLabel();
        ButtonSimpan = new javax.swing.JButton();
        ButtonBatal = new javax.swing.JButton();
        JwbJudulBuku = new javax.swing.JTextField();
        JwbKodeBuku = new javax.swing.JTextField();
        JwbPenulisBuku = new javax.swing.JTextField();
        JwbKategoriBuku = new javax.swing.JTextField();
        JwbJumlahBukuTersedia = new javax.swing.JTextField();
        DialogEdit = new javax.swing.JDialog();
        LabelPengeditanInformasiBuku = new javax.swing.JLabel();
        Labeljudulbuku = new javax.swing.JLabel();
        Labelkodebuku = new javax.swing.JLabel();
        Labelpenulisbuku = new javax.swing.JLabel();
        Labelkategoribuku = new javax.swing.JLabel();
        Labeljumlahbukutersedia = new javax.swing.JLabel();
        jButtonSimpan = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        JwbnJudulBuku = new javax.swing.JTextField();
        JwbnKodeBuku = new javax.swing.JTextField();
        JwbnPenulisBuku = new javax.swing.JTextField();
        JwbnKategoriBuku = new javax.swing.JTextField();
        JwbnJumlahBukuTersedia = new javax.swing.JTextField();
        LabelManajemenBuku = new javax.swing.JLabel();
        ButtonDashboard = new javax.swing.JButton();
        ButtonBuku = new javax.swing.JButton();

        javax.swing.GroupLayout DialogDashboardLayout = new javax.swing.GroupLayout(DialogDashboard.getContentPane());
        DialogDashboard.getContentPane().setLayout(DialogDashboardLayout);
        DialogDashboardLayout.setHorizontalGroup(
            DialogDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DialogDashboardLayout.setVerticalGroup(
            DialogDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        LabelDaftarBuku.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        LabelDaftarBuku.setText("Daftar Buku");

        LabelJudulbuku.setText("Judul Buku                    :");

        LabelKodebuku.setText("Kode Buku                    :");

        LabelPenulisbuku.setText("Penulis Buku                 :");

        LabelKategoribuku.setText("Kategori Buku              :");

        LabelJumlahbukutersedia.setText("Jumlah Buku Tersedia  :");

        JawabanPenulisBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JawabanPenulisBukuActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Judul Buku", "Kode Buku", "Penulis Buku", "Kategori Buku", "Jumlah Buku Tersedia"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ButtonTambah.setText("Tambah");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });

        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonHapus.setText("Hapus");

        javax.swing.GroupLayout DialogBukuLayout = new javax.swing.GroupLayout(DialogBuku.getContentPane());
        DialogBuku.getContentPane().setLayout(DialogBukuLayout);
        DialogBukuLayout.setHorizontalGroup(
            DialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogBukuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelDaftarBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
            .addGroup(DialogBukuLayout.createSequentialGroup()
                .addGroup(DialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogBukuLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(DialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelJumlahbukutersedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelKategoribuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelPenulisbuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelKodebuku, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(LabelJudulbuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(DialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JawabanJudulBuku)
                            .addComponent(JawabanKodeBuku)
                            .addComponent(JawabanPenulisBuku)
                            .addComponent(JawabanKategoriBuku)
                            .addComponent(JawabanJumlahBukuTersedia, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)))
                    .addGroup(DialogBukuLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DialogBukuLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(ButtonTambah)
                        .addGap(51, 51, 51)
                        .addComponent(ButtonEdit)
                        .addGap(52, 52, 52)
                        .addComponent(ButtonHapus)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        DialogBukuLayout.setVerticalGroup(
            DialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogBukuLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(LabelDaftarBuku)
                .addGap(47, 47, 47)
                .addGroup(DialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJudulbuku)
                    .addComponent(JawabanJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(DialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKodebuku)
                    .addComponent(JawabanKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(DialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPenulisbuku)
                    .addComponent(JawabanPenulisBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(DialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKategoribuku)
                    .addComponent(JawabanKategoriBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(DialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJumlahbukutersedia)
                    .addComponent(JawabanJumlahBukuTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(DialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTambah)
                    .addComponent(ButtonEdit)
                    .addComponent(ButtonHapus))
                .addGap(22, 22, 22))
        );

        LabelPenambahanBuku.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        LabelPenambahanBuku.setText("Penambahan Buku");

        LabelJudulBuku.setText("Judul Buku                     :");

        LabelKodeBuku.setText("Kode Buku                    :");

        LabelPenulisBuku.setText("Penulis Buku                 :");

        LabelKategoriBuku.setText("Kategori Buku              :");

        LabelJumlahBukuTersedia.setText("Jumlah Buku Tersedia  :");

        ButtonSimpan.setText("Simpan");

        ButtonBatal.setText("Batal");

        javax.swing.GroupLayout DialogTambahLayout = new javax.swing.GroupLayout(DialogTambah.getContentPane());
        DialogTambah.getContentPane().setLayout(DialogTambahLayout);
        DialogTambahLayout.setHorizontalGroup(
            DialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogTambahLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(DialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelJumlahBukuTersedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelKategoriBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelPenulisBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelKodeBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelJudulBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JwbJudulBuku)
                    .addComponent(JwbKodeBuku)
                    .addComponent(JwbPenulisBuku)
                    .addComponent(JwbKategoriBuku)
                    .addComponent(JwbJumlahBukuTersedia, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogTambahLayout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addGroup(DialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogTambahLayout.createSequentialGroup()
                        .addComponent(ButtonSimpan)
                        .addGap(45, 45, 45)
                        .addComponent(ButtonBatal)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogTambahLayout.createSequentialGroup()
                        .addComponent(LabelPenambahanBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))))
        );
        DialogTambahLayout.setVerticalGroup(
            DialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogTambahLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(LabelPenambahanBuku)
                .addGap(56, 56, 56)
                .addGroup(DialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJudulBuku)
                    .addComponent(JwbJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(DialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKodeBuku)
                    .addComponent(JwbKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(DialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPenulisBuku)
                    .addComponent(JwbPenulisBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(DialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKategoriBuku)
                    .addComponent(JwbKategoriBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(DialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJumlahBukuTersedia)
                    .addComponent(JwbJumlahBukuTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(DialogTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSimpan)
                    .addComponent(ButtonBatal))
                .addGap(38, 38, 38))
        );

        LabelPengeditanInformasiBuku.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        LabelPengeditanInformasiBuku.setText("Pengeditan Informasi Buku");

        Labeljudulbuku.setText("Judul Buku                   :");

        Labelkodebuku.setText("Kode Buku                   :");

        Labelpenulisbuku.setText("Penulis Buku                 :");

        Labelkategoribuku.setText("Kategori Buku              :");

        Labeljumlahbukutersedia.setText("Jumlah Buku Tersedia  :");

        jButtonSimpan.setText("Simpan");

        jButtonBatal.setText("Batal");

        javax.swing.GroupLayout DialogEditLayout = new javax.swing.GroupLayout(DialogEdit.getContentPane());
        DialogEdit.getContentPane().setLayout(DialogEditLayout);
        DialogEditLayout.setHorizontalGroup(
            DialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogEditLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(DialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Labeljumlahbukutersedia, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(Labelkategoribuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Labelpenulisbuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Labelkodebuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Labeljudulbuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JwbnJudulBuku)
                    .addComponent(JwbnKodeBuku)
                    .addComponent(JwbnPenulisBuku)
                    .addComponent(JwbnKategoriBuku)
                    .addComponent(JwbnJumlahBukuTersedia, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogEditLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(DialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogEditLayout.createSequentialGroup()
                        .addComponent(jButtonSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBatal)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogEditLayout.createSequentialGroup()
                        .addComponent(LabelPengeditanInformasiBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );
        DialogEditLayout.setVerticalGroup(
            DialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogEditLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(LabelPengeditanInformasiBuku)
                .addGap(50, 50, 50)
                .addGroup(DialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labeljudulbuku)
                    .addComponent(JwbnJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(DialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labelkodebuku)
                    .addComponent(JwbnKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(DialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labelpenulisbuku)
                    .addComponent(JwbnPenulisBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(DialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labelkategoribuku)
                    .addComponent(JwbnKategoriBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(DialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Labeljumlahbukutersedia)
                    .addComponent(JwbnJumlahBukuTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(DialogEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSimpan)
                    .addComponent(jButtonBatal))
                .addGap(33, 33, 33))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelManajemenBuku.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LabelManajemenBuku.setText("Manajemen Buku");

        ButtonDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonDashboard.setText("Dashboard");

        ButtonBuku.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonBuku.setText("Buku");
        ButtonBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(ButtonDashboard)
                .addGap(18, 18, 18)
                .addComponent(ButtonBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(LabelManajemenBuku)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(LabelManajemenBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBukuActionPerformed

    private void JawabanPenulisBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JawabanPenulisBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JawabanPenulisBukuActionPerformed

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManajemenBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManajemenBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManajemenBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManajemenBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManajemenBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBatal;
    private javax.swing.JButton ButtonBuku;
    private javax.swing.JButton ButtonDashboard;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JDialog DialogBuku;
    private javax.swing.JDialog DialogDashboard;
    private javax.swing.JDialog DialogEdit;
    private javax.swing.JDialog DialogTambah;
    private javax.swing.JTextField JawabanJudulBuku;
    private javax.swing.JTextField JawabanJumlahBukuTersedia;
    private javax.swing.JTextField JawabanKategoriBuku;
    private javax.swing.JTextField JawabanKodeBuku;
    private javax.swing.JTextField JawabanPenulisBuku;
    private javax.swing.JTextField JwbJudulBuku;
    private javax.swing.JTextField JwbJumlahBukuTersedia;
    private javax.swing.JTextField JwbKategoriBuku;
    private javax.swing.JTextField JwbKodeBuku;
    private javax.swing.JTextField JwbPenulisBuku;
    private javax.swing.JTextField JwbnJudulBuku;
    private javax.swing.JTextField JwbnJumlahBukuTersedia;
    private javax.swing.JTextField JwbnKategoriBuku;
    private javax.swing.JTextField JwbnKodeBuku;
    private javax.swing.JTextField JwbnPenulisBuku;
    private javax.swing.JLabel LabelDaftarBuku;
    private javax.swing.JLabel LabelJudulBuku;
    private javax.swing.JLabel LabelJudulbuku;
    private javax.swing.JLabel LabelJumlahBukuTersedia;
    private javax.swing.JLabel LabelJumlahbukutersedia;
    private javax.swing.JLabel LabelKategoriBuku;
    private javax.swing.JLabel LabelKategoribuku;
    private javax.swing.JLabel LabelKodeBuku;
    private javax.swing.JLabel LabelKodebuku;
    private javax.swing.JLabel LabelManajemenBuku;
    private javax.swing.JLabel LabelPenambahanBuku;
    private javax.swing.JLabel LabelPengeditanInformasiBuku;
    private javax.swing.JLabel LabelPenulisBuku;
    private javax.swing.JLabel LabelPenulisbuku;
    private javax.swing.JLabel Labeljudulbuku;
    private javax.swing.JLabel Labeljumlahbukutersedia;
    private javax.swing.JLabel Labelkategoribuku;
    private javax.swing.JLabel Labelkodebuku;
    private javax.swing.JLabel Labelpenulisbuku;
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
