/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemperpus;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author candr
 */
public class Pinjam extends javax.swing.JFrame {

    /**
     * Creates new form PinjamLagi
     */
    public Pinjam() {
        initComponents();
        dt();
        scaleImage();
    }
    public void dt(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        String dat = s.format(d);
        label_date.setText(dat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputMemberID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputBookID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        label_date = new javax.swing.JLabel();
        buttonBorrow = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        gambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Issue Books");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 17, -1, -1));

        jLabel4.setText("Member ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 133, -1, -1));
        getContentPane().add(inputMemberID, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 130, 191, -1));

        jLabel5.setText("Book ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 63, -1, -1));

        inputBookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBookIDActionPerformed(evt);
            }
        });
        getContentPane().add(inputBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 60, 191, -1));

        jLabel6.setText("Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 170, -1, -1));

        label_date.setText("jLabel7");
        getContentPane().add(label_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 170, -1, -1));

        buttonBorrow.setBackground(new java.awt.Color(255, 153, 153));
        buttonBorrow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonBorrow.setText("Borrow");
        buttonBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrowActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBorrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 237, -1, 32));

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 237, 80, 32));

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 237, 80, 32));
        getContentPane().add(gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -8, 510, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrowActionPerformed
        String bookID = inputBookID.getText();
        String memberID = inputMemberID.getText();
        
        // tanggal peminjaman dan tanggal maksimal pengembalian
        LocalDate loanDate = LocalDate.now();
        LocalDate dueDate = loanDate.plusDays(5);
        
        Connection connection = DatabaseConnection.getConnection();
        Statement statement = null;
        try {
            statement = connection.createStatement();
            
            //mengecek buku
            String sql = "SELECT book_id FROM books";
            ResultSet result = statement.executeQuery(sql);
            boolean bookFound = false;
            boolean memberFound = false;
            while(result.next()){
                if(result.getString("book_id").equals(bookID)){
                    //mengecek member
                    
                    sql = "SELECT member_id FROM member";
                    result = statement.executeQuery(sql);
                    while(result.next()){
                        if(result.getString("member_id").equals(memberID)){
                            
                            memberFound = true;
                            break;
                        }
                    }
                    if (!memberFound) {
                        JOptionPane.showMessageDialog(this, "Member not found", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    bookFound = true;
                    break;
                }
            }
            if (!bookFound) {
                JOptionPane.showMessageDialog(this, "Book not found", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            // menginput data ke tabel peminjaman
            if(memberFound && bookFound){
                String loanQuery = "INSERT INTO loan_items (book_id, member_id, loan_date, due_date) VALUES (?,?,?,?)";
                PreparedStatement preparedStatement = connection.prepareStatement(loanQuery);
                preparedStatement.setString(1, bookID);
                preparedStatement.setString(2, memberID);
                preparedStatement.setDate(3, java.sql.Date.valueOf(loanDate));
                preparedStatement.setDate(4, java.sql.Date.valueOf(dueDate));
                preparedStatement.executeUpdate();
                
                // mengupdate jumlah stock buku pada tabel buku
                String updateStockQuery = "UPDATE Books SET available_stock = available_stock - 1 WHERE book_id = ?";
                preparedStatement = connection.prepareStatement(updateStockQuery);
                preparedStatement.setString(1, bookID);
                preparedStatement.executeUpdate();
                preparedStatement.close();
                JOptionPane.showMessageDialog(this, "Book successfully borrowed", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }catch (SQLIntegrityConstraintViolationException e){
            JOptionPane.showMessageDialog(this, "The book is already borrowed", "Error", JOptionPane.ERROR_MESSAGE);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Something wrong, i can feel it", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_buttonBorrowActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        inputBookID.setText("");
        inputMemberID.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        super.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void inputBookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBookIDActionPerformed
public void scaleImage(){
        ImageIcon icon = new ImageIcon("1.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(gambar.getWidth(), gambar.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        gambar.setIcon(scaledIcon);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pinjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBorrow;
    private javax.swing.JLabel gambar;
    private javax.swing.JTextField inputBookID;
    private javax.swing.JTextField inputMemberID;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel label_date;
    // End of variables declaration//GEN-END:variables

}
