/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemperpus;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author candr
 */
public class Return extends javax.swing.JFrame {

    /**
     * Creates new form ReturnLagi
     */
    public Return() {
        initComponents();
        scaleImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        buttonSearch = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        inputMemberID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputLateFee = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputBookTitle = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputBookID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputIssueDate = new javax.swing.JTextField();
        buttonReturn = new javax.swing.JButton();
        gambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Return Books");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Member ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 141, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Title", "Loan Date", "Due Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 61, -1, 217));

        buttonSearch.setBackground(new java.awt.Color(255, 153, 153));
        buttonSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 186, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Back");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 186, -1, -1));

        inputMemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMemberIDActionPerformed(evt);
            }
        });
        getContentPane().add(inputMemberID, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 138, 112, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Book   Title");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 340, 70, -1));

        inputLateFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLateFeeActionPerformed(evt);
            }
        });
        getContentPane().add(inputLateFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 403, 144, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Issue   Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 370, 70, -1));

        inputBookTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBookTitleActionPerformed(evt);
            }
        });
        getContentPane().add(inputBookTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 335, 144, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Book    ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 310, 60, -1));

        inputBookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBookIDActionPerformed(evt);
            }
        });
        getContentPane().add(inputBookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 301, 144, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Late    Fee");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 400, 60, -1));

        inputIssueDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIssueDateActionPerformed(evt);
            }
        });
        getContentPane().add(inputIssueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 369, 144, -1));

        buttonReturn.setBackground(new java.awt.Color(255, 153, 153));
        buttonReturn.setText("Return");
        buttonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReturnActionPerformed(evt);
            }
        });
        getContentPane().add(buttonReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 403, -1, -1));
        getContentPane().add(gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -8, 860, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void loanTable(String keyword){
        Connection connection = DatabaseConnection.getConnection();
        PreparedStatement preparedStatement = null;
        try{
            // menggabungkan tabel loan_items dan books
            String sql = "SELECT loan_items.*, books.title FROM loan_items INNER JOIN books ON loan_items.book_id = books.book_id WHERE loan_items.member_id = ?";
            preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, keyword);
            ResultSet result = preparedStatement.executeQuery();
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            DefaultTableModel tableModel = (DefaultTableModel)table.getModel();
            tableModel.setRowCount(0);
            while(result.next()){
                String bookID = result.getString("book_id");
                String title = result.getString("title");
                Date loanDate = result.getDate("loan_date");
                Date dueDate = result.getDate("due_date");
                
                // format date
                String formattedLoanDate = dateFormat.format(loanDate);
                String formattedDueDate = dateFormat.format(dueDate);
                
                //memasukkan data ke dalam tabel
                String tableData[] = {bookID, title, formattedLoanDate, formattedDueDate};
                tableModel.addRow(tableData);
                
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Something wrong", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        String memberID = inputMemberID.getText();
        
        this.loanTable(memberID);
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void inputMemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMemberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMemberIDActionPerformed

    private void inputLateFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLateFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLateFeeActionPerformed

    private void inputBookTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBookTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBookTitleActionPerformed

    private void inputBookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBookIDActionPerformed

    private void inputIssueDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIssueDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIssueDateActionPerformed

    private void buttonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReturnActionPerformed
        String bookID = inputBookID.getText();
        String memberID = inputMemberID.getText();
        
        Connection connection = DatabaseConnection.getConnection();
        try{
            String sql = "DELETE FROM loan_items WHERE book_id = ?";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            preparedStatement.setString(1, bookID);
            preparedStatement.executeUpdate();
            String sqlUpdate = "UPDATE books SET available_stock = 1 ";
            preparedStatement = connection.prepareStatement(sqlUpdate);
            preparedStatement.executeUpdate();
            this.loanTable(memberID);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Something wrong, i can feel it", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }//GEN-LAST:event_buttonReturnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int i = table.getSelectedRow();
        TableModel model = table.getModel();
        inputBookID.setText(model.getValueAt(i, 0).toString());
        inputBookTitle.setText(model.getValueAt(i, 1).toString());
        String issueDate = model.getValueAt(i, 2).toString();
        inputIssueDate.setText(issueDate);
        
        // Mengubah string menjadi objek LocalDate
        LocalDate formattedIssueDate = LocalDate.parse(issueDate, DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        LocalDate currentDate = LocalDate.now();
        int days = Period.between(formattedIssueDate, currentDate).getDays();
        if(days<=5){
            inputLateFee.setText("Rp 0");
        }else{
            int fee = 1000*(days-5);
            inputLateFee.setText("Rp " + Integer.toString(fee));
        }
    }//GEN-LAST:event_tableMouseClicked
public void scaleImage(){
        ImageIcon icon = new ImageIcon("1.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(gambar.getWidth(), gambar.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        gambar.setIcon(scaledIcon);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonReturn;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JLabel gambar;
    private javax.swing.JTextField inputBookID;
    private javax.swing.JTextField inputBookTitle;
    private javax.swing.JTextField inputIssueDate;
    private javax.swing.JTextField inputLateFee;
    private javax.swing.JTextField inputMemberID;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
